### ISSUE TITLE
About storing the registration in the database

### ISSUE THREAD

**Issue by takusng** [sipatel2/shibboleth-webauthn#7]
I'd like to set this plugin to my university's IdP.
It's written that "The registration is stored in memory only. In production, Duke is storing registration data in a database using a modified version of RegistrationStorage.java.". If I'd like to store the registration in my IdP's database, should I just replace the RegistrationStorage.java file to the misc directory's one? But, this java file declares "import edu.duke.oit.idms.idp.authn.dbconn.DatabaseConnectionFactory", so could you provide this package?

**Comment by sipatel2** [comment]
I added some sample code in the misc folder.  It uses pooling to get a database connection.  It also references IdMClientConfig which is an internal class that uses our secret store to retrieve configuration.
